import { useState, useEffect, useRef } from "react";
import { FF, FFB, FFM } from "../ui/styles.js";
import { fill, bdr, hexRgb } from "../lib/format.js";
import { playSound } from "../lib/audio.js";

export function SnakeApp({AC}){
  const GRID=20,CELL=18,W=GRID*CELL,H=GRID*CELL;const canvasRef=useRef(null);const [phase,setPhase]=useState("idle");const [score,setScore]=useState(0);const [best,setBest]=useState(0);
  const st=useRef({snake:[{x:10,y:10},{x:9,y:10},{x:8,y:10}],dir:{x:1,y:0},nextDir:{x:1,y:0},food:{x:15,y:8},score:0});const intv=useRef(null);
  function randFood(s){let p;do{p={x:Math.floor(Math.random()*GRID),y:Math.floor(Math.random()*GRID)};}while(s.some(x=>x.x===p.x&&x.y===p.y));return p;}
  function draw(){const c=canvasRef.current;if(!c)return;const ctx=c.getContext("2d");ctx.fillStyle="#0a0a14";ctx.fillRect(0,0,W,H);ctx.strokeStyle="rgba(255,255,255,0.03)";for(let i=0;i<GRID;i++){ctx.beginPath();ctx.moveTo(i*CELL,0);ctx.lineTo(i*CELL,H);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*CELL);ctx.lineTo(W,i*CELL);ctx.stroke();}const f=st.current.food;ctx.fillStyle="#ff4444";ctx.beginPath();ctx.arc(f.x*CELL+CELL/2,f.y*CELL+CELL/2,CELL/2-2,0,Math.PI*2);ctx.fill();st.current.snake.forEach((seg,i)=>{ctx.fillStyle=i===0?AC:"rgba("+hexRgb(AC)+","+(Math.max(0.3,0.9-i*0.015))+")";ctx.beginPath();if(ctx.roundRect)ctx.roundRect(seg.x*CELL+1,seg.y*CELL+1,CELL-2,CELL-2,3);else ctx.rect(seg.x*CELL+1,seg.y*CELL+1,CELL-2,CELL-2);ctx.fill();});}
  function tick(){const s=st.current;s.dir=s.nextDir;const head={x:s.snake[0].x+s.dir.x,y:s.snake[0].y+s.dir.y};if(head.x<0||head.x>=GRID||head.y<0||head.y>=GRID||s.snake.some(seg=>seg.x===head.x&&seg.y===head.y)){clearInterval(intv.current);setBest(b=>Math.max(b,s.score));setPhase("over");return;}s.snake.unshift(head);if(head.x===s.food.x&&head.y===s.food.y){s.score++;setScore(s.score);s.food=randFood(s.snake);}else s.snake.pop();draw();}
  function start(){st.current={snake:[{x:10,y:10},{x:9,y:10},{x:8,y:10}],dir:{x:1,y:0},nextDir:{x:1,y:0},food:randFood([]),score:0};setScore(0);setPhase("playing");clearInterval(intv.current);intv.current=setInterval(tick,130);draw();}
  useEffect(()=>{if(phase!=="playing")return;const DM={ArrowUp:{x:0,y:-1},w:{x:0,y:-1},W:{x:0,y:-1},ArrowDown:{x:0,y:1},s:{x:0,y:1},S:{x:0,y:1},ArrowLeft:{x:-1,y:0},a:{x:-1,y:0},A:{x:-1,y:0},ArrowRight:{x:1,y:0},d:{x:1,y:0},D:{x:1,y:0}};function onKey(e){const d=DM[e.key];if(!d)return;e.preventDefault();const s=st.current;if(d.x===-s.dir.x&&d.y===-s.dir.y)return;s.nextDir=d;}window.addEventListener("keydown",onKey);return()=>{window.removeEventListener("keydown",onKey);clearInterval(intv.current);};},[phase]);
  useEffect(()=>{draw();},[]);
  return(<div style={{width:"100%",fontFamily:FF,display:"flex",flexDirection:"column",alignItems:"center",gap:10}}><div style={{display:"flex",gap:24,width:"100%",maxWidth:W}}><div style={{fontFamily:FFB,fontWeight:600,fontSize:14,color:AC}}>🐍 SNAKE</div><div style={{flex:1}}/><div style={{fontFamily:FFM,fontSize:12,color:"rgba(255,255,255,0.6)"}}>Score: {score}</div><div style={{fontFamily:FFM,fontSize:12,color:"rgba(255,255,255,0.4)"}}>Best: {best}</div></div><div style={{position:"relative",width:"100%",maxWidth:W}}><canvas ref={canvasRef} width={W} height={H} style={{width:"100%",height:"auto",display:"block",borderRadius:8,border:"1px solid rgba(255,255,255,0.08)"}}/>{(phase==="idle"||phase==="over")&&(<div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:14,background:"rgba(7,8,15,0.75)",borderRadius:8}}>{phase==="over"&&<><div style={{fontFamily:FFB,fontSize:20,color:"#ff4444",fontWeight:700}}>Game Over</div><div style={{fontFamily:FFM,fontSize:14,color:"rgba(255,255,255,0.6)"}}>Score: {score}</div></>}<button onClick={start} style={{padding:"11px 32px",background:fill(AC),border:"1px solid "+bdr(AC),borderRadius:8,cursor:"pointer",fontFamily:FFB,fontWeight:700,fontSize:15,color:AC}}>{phase==="over"?"Play Again":"Start Game"}</button>{phase==="idle"&&<div style={{fontSize:11,color:"rgba(255,255,255,0.3)",fontFamily:FF}}>Arrow keys or WASD to move</div>}</div>)}</div></div>);
}
